### ISSUE TITLE
dupe leashes

### ISSUE THREAD

**Issue by Kotarych** [WMGameLive/LeashPlayers#1]
if you fly to the elite, then the leash is duped, they fall out 2 instead of 1, there may still be a dupe (I write through a translator)

**Comment by WMGameLive** [comment]
thank you for the report, I will check the problem as soon as possible.

**Comment by WMGameLive** [comment]
this bug will be fixed in version 1.2.

**Comment by INotSleep** [comment]
Dupe still works
