### ISSUE TITLE
the plugin does not work for me, as if it was uploaded to the server, but the player is not taken on a leash.

### ISSUE THREAD

**Issue by dsfsdf2133** [WMGameLive/LeashPlayers#4]
the plugin does not work for me, as if it was uploaded to the server, but the player is not taken on a leash.

**Comment by dsfsdf2133** [comment]
No, the server used version 1.16.5

**Comment by WMGameLive** [comment]
> No, the server used version 1.16.5

I will test it, thank you for the report.

**Comment by WMGameLive** [comment]
it is work for me on 1.16.5, did you remember to give the player leashplayer.use permission?

**Comment by WMGameLive** [comment]
Closed due to no reply for a long time.
